title: COMP 5270 - HCI*
description: A website for the Human-Computer Interaction class at UMass Lowell.
theme: just-the-docs

url: https://uml-hci.github.io/comp5270-s25

# Aux links for the upper right navigation
aux_links:
  "COMP5270 on Blackboard":
    - "https://uml.umassonline.net/ultra/courses/_62886_1/cl/outline"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true
